//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfulAPI_Gamer.Areas.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assistance
    {
        public int IdEvent { get; set; }
        public int IdUser { get; set; }
        public Nullable<int> State { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Users Users { get; set; }
    }
}
