//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfulAPI_Gamer.Areas.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cabin
    {
        public Cabin()
        {
            this.Event = new HashSet<Event>();
        }
    
        public int IdCabin { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> StateAttention { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> State { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Event> Event { get; set; }
    }
}
