//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfulAPI_Gamer.Areas.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.UserComment = new HashSet<UserComment>();
        }
    
        public int IdComment { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Mylike { get; set; }
        public Nullable<int> IdUser { get; set; }
        public int IdPublication { get; set; }
        public Nullable<int> State { get; set; }
    
        public virtual Publication Publication { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<UserComment> UserComment { get; set; }
    }
}
