//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfulAPI_Gamer.Areas.Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDGamerEntities : DbContext
    {
        public BDGamerEntities()
            : base("name=BDGamerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Assistance> Assistance { get; set; }
        public DbSet<Cabin> Cabin { get; set; }
        public DbSet<Comment> Comment { get; set; }
        public DbSet<Event> Event { get; set; }
        public DbSet<Game> Game { get; set; }
        public DbSet<Gamer> Gamer { get; set; }
        public DbSet<Publication> Publication { get; set; }
        public DbSet<UserComment> UserComment { get; set; }
        public DbSet<UserPublication> UserPublication { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
