//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfulAPI_Gamer.Areas.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Assistance = new HashSet<Assistance>();
        }
    
        public int IdEvent { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> IdCabin { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> DateEvent { get; set; }
        public Nullable<int> State { get; set; }
    
        public virtual ICollection<Assistance> Assistance { get; set; }
        public virtual Cabin Cabin { get; set; }
    }
}
