//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfulAPI_Gamer.Areas.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Publication = new HashSet<Publication>();
        }
    
        public int idGame { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> State { get; set; }
    
        public virtual ICollection<Publication> Publication { get; set; }
    }
}
