//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfulAPI_Gamer.Areas.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        public Publication()
        {
            this.Comment = new HashSet<Comment>();
            this.UserPublication = new HashSet<UserPublication>();
        }
    
        public int IdPublication { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateRegister { get; set; }
        public Nullable<int> idGame { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> IdUser { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Game Game { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<UserPublication> UserPublication { get; set; }
    }
}
